# References
# https://docs.github.com/en/actions/writing-workflows/quickstart
# https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-java-with-gradle
# https://github.com/gradle/actions

# Workflow name
name: Object Detector GitHub Actions

# Workflow title
run-name: ${{ github.actor }} is cooking up some GitHub Actions
on: [push]
jobs:
  GitHub-Actions:
    runs-on: ubuntu-latest
    env:
      RELEASE_JKS_FILE_BASE64: ${{ secrets.RELEASE_JKS_FILE_BASE64 }}
      RELEASE_JSK_PASSWORD: ${{ secrets.RELEASE_JSK_PASSWORD }}
      RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
      RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
    steps:
      - run: echo "The job was triggered by ${{ github.event_name }} event. Branch ${{ github.ref }}"

      # Clone repo
      - name: Check out repo code
        uses: actions/checkout@v4

      - run: echo "The ${{ github.repository }} repo has been cloned to the runner."

      - name: List files in the repo
        run: |
          ls ${{ github.workspace }}

      # Setup java
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Set up gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.7'

      # Grants execute permission to gradle
      - name: Grant Permissions to gradlew
        run: chmod +x gradlew

      # build also runs tests, so just run release .apk:
      # ./gradlew assembleRelease
      - name: Build app
        run: ./gradlew assembleRelease

      - run: echo "Job's status is ${{ job.status }}."
